### ISSUE TITLE
How can I pipe souphttpsrc instead of my screen?

### ISSUE THREAD

**Issue by invasionofsmallcubes** [joanrieu/gst-live#3]
Hi, the script works flawlessly as intended. I was wondering if you could tell me how to remove the screen part to use https://gstreamer.freedesktop.org/documentation/soup/souphttpsrc.html?gi-language=c as I would like to stream a webpage as source.

Thank you for your help.

**Comment by joanrieu** [comment]
Hello, you should be able to do that by editing `config.sh` and using a new `add_src` line. You can use the regular gstreamer syntax on that line, so something like `add_src souphttpsrc` + any additional parameter you need for that source. You can remove the webcam or desktop or both by commenting out the relevant lines in the same file.

**Comment by invasionofsmallcubes** [comment]
thanks!
